language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  app: siget-mantenimiento
  on:
    branch: develop
  api_key:
    secure: Lo8l+562BidRNKGfzTUoaRAphWQBGvlfY9hcAoct9m69gpD32nDUINUau5bhVLlwNvrwNKT5XH96OPJAJ/oGBx2kHjztm42yD6ntEUnTZ6yMpIVUFko9Ewv9VcrR4ruW2PY+8+u3EYA2a5uX5wXiokNr0NW+JCLbIzwTYthwQSBCgtOEVdgOrRjnC66eGtOOtXx5Z+13BqiLXzPLdPt+NuJnazMLwBAHrVQ09QAgKKlOEpeykuSTbaJd7mnkDsoV56Yz4IjIl/Ew8XEUKMR7ySqCX8g4pokw5gjyTpCAtzyh7K75ViL1itPzf8udGIUf40XF4yCFXDYebLPFgaDrueoBcz3yFHsLW1jOs7kR01zMQ22F0WgCPOg9SqPSYFJbDWES3mcTzo3vlb0dzlSKhH4V+rCBUlg4tYU4xDntiXpoi1wYzkZrzSTelZUJy1Li9G2XbRCzQoDPPg1NjPDVQ2oEllfmfTujOqYb///I1geTa8Ie16y2qgC4s6qhW9dDsVV9Ef/Lc//RyK6safH8YB4Bsf9nhPbXsnmlC1HP+dbRiwr3pkBrhHYvCniycfkzuSZej3zHpn8537YrsOqyGdgh1K678A+XUjExmF2bseBQaunO7ha6e4mW/RWSqo8UpZQJGDN8nB2U63nY8I5W91W65hgPWs3Y7D9sbZ73tmk=
